version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ropa20932060
        MYSQL_DATABASE: app
        MYSQL_USER: nkcuser
        MYSQL_PASSWORD: nkcusersspa
        TZ: 'Asia/Tokyo'
    ports:
        - "4306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    build: ./docker/php
    volumes:
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["mysql"]

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/html:/usr/share/nginx/html
    restart: always
    ports:
      - "80:80"
    depends_on: ["php"]